#BY JP-VP:
#  por enquanto vou deixar sem o MySQL e o phpmyadmin. Pois ainda n está sendo necessário :)
version: '3.8'
services:
  php_apache:
    container_name: php_apache
    hostname: php_apache
    image: php:8.3.7-apache-bookworm
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    restart: always

